[build]
    base = "01-Login"
    command = "printf '{\"domain\":\"%s\", \"clientId\":\"%s\"}' \"${AUTH0_DOMAIN}\" \"${AUTH0_CLIENT_ID}\" > public/auth_config.json && cp index.html public"
    publish = "public"

